### ISSUE TITLE
Git Push Resin Master Failure

### ISSUE THREAD

**Issue by MPDamiano** [resin-io-playground/office-lock#2]
Matthew@Matthew-Dell MINGW64 ~/office-lock (master)
$ git push resin master
Enter passphrase for key '/c/Users/Matthew/.ssh/id_rsa':
Counting objects: 40, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (40/40), 1.72 MiB | 9.65 MiB/s, done.
Total 40 (delta 14), reused 0 (delta 0)

[Info]     Starting build for damianm/newlock, user damianm
[Info]     Dashboard link: https://dashboard.resin.io/apps/978253/devices
[Info]     Building on arm03
[Info]     Fetching base image
[Warning]  No image tag given for resin/raspberrypi3-python, using default (late                                                                                            st)
[==================================================>] 100%
[Info]     Building Dockerfile.template project
[Build]    Step 1/10 : FROM resin/raspberrypi3-python
[Build]     ---> 08c2228b0ec6
[Build]    Step 2/10 : RUN apt-get update && apt-get install -yq     build-essen                                                                                            tial     python-dev     git     scons     swig &&     apt-get clean && rm -rf /v                                                                                            ar/lib/apt/lists/*
[Build]     ---> Running in 3e1972c9254a
[Build]    Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
[Build]    Get:2 http://archive.raspbian.org jessie InRelease [14.9 kB]
[Build]    Get:3 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
[Build]    Ign http://deb.debian.org jessie InRelease
[Build]    Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]
[Build]    Get:5 http://deb.debian.org jessie Release.gpg [2434 B]
[Build]    Get:6 http://deb.debian.org jessie Release [148 kB]
[Build]    Get:7 http://security.debian.org jessie/updates/main armhf Packages [593 kB]
[Build]    Get:8 http://archive.raspbian.org jessie/main armhf Packages [13.3 MB]
[Build]    Get:9 http://archive.raspberrypi.org jessie/main armhf Packages [171 kB]
[Build]    Get:10 http://archive.raspbian.org jessie/contrib armhf Packages [49.5 kB]
[Build]    Get:11 http://archive.raspbian.org jessie/non-free armhf Packages [101 kB]
[Build]    Get:12 http://archive.raspbian.org jessie/rpi armhf Packages [1297 B]
[Build]    Get:13 http://archive.raspbian.org jessie/firmware armhf Packages [1202 B]
[Build]    Get:14 http://deb.debian.org jessie-updates/main armhf Packages [23.1 kB]
[Build]    Get:15 http://deb.debian.org jessie/main armhf Packages [8864 kB]
[Build]    Fetched 23.5 MB in 10s (2180 kB/s)
[Build]    Reading package lists...
[Build]    Reading package lists...
[Build]    Building dependency tree...
[Build]    Reading state information...
[Build]    build-essential is already the newest version.
[Build]    git is already the newest version.
[Build]    The following extra packages will be installed:
[Build]      libexpat1-dev libpython-dev libpython2.7 libpython2.7-dev python2.7-dev
[Build]      swig2.0
[Build]    Suggested packages:
[Build]      swig-doc swig-examples swig2.0-examples swig2.0-doc
[Build]    The following NEW packages will be installed:
[Build]      libexpat1-dev libpython-dev libpython2.7 libpython2.7-dev python-dev
[Build]      python2.7-dev scons swig swig2.0
[Build]    0 upgraded, 9 newly installed, 0 to remove and 12 not upgraded.
[Build]    Need to get 21.2 MB of archives.
[Build]    After this operation, 34.4 MB of additional disk space will be used.
[Build]    Get:1 http://deb.debian.org/debian/ jessie/main libpython2.7 armhf 2.7.9-2+deb8u1 [949 kB]
[Build]    Get:2 http://deb.debian.org/debian/ jessie/main libexpat1-dev armhf 2.1.0-6+deb8u4 [115 kB]
[Build]    Get:3 http://deb.debian.org/debian/ jessie/main libpython2.7-dev armhf 2.7.9-2+deb8u1 [18.0 MB]
[Build]    Get:4 http://deb.debian.org/debian/ jessie/main libpython-dev armhf 2.7.9-1 [19.7 kB]
[Build]    Get:5 http://deb.debian.org/debian/ jessie/main python2.7-dev armhf 2.7.9-2+deb8u1 [284 kB]
[Build]    Get:6 http://deb.debian.org/debian/ jessie/main python-dev armhf 2.7.9-1 [1180 B]
[Build]    Get:7 http://deb.debian.org/debian/ jessie/main scons all 2.3.1-2 [518 kB]
[Build]    Get:8 http://deb.debian.org/debian/ jessie/main swig2.0 armhf 2.0.12-1 [1077 kB]
[Build]    Get:9 http://deb.debian.org/debian/ jessie/main swig armhf 2.0.12-1 [285 kB]
[Build]    debconf: delaying package configuration, since apt-utils is not installed
[Build]    Fetched 21.2 MB in 2s (9739 kB/s)
[Build]    Selecting previously unselected package libpython2.7:armhf.
(Reading database ... 18219 files and directories currently installed.)
[Build]    Preparing to unpack .../libpython2.7_2.7.9-2+deb8u1_armhf.deb ...
[Build]    Unpacking libpython2.7:armhf (2.7.9-2+deb8u1) ...
[Build]    Selecting previously unselected package libexpat1-dev:armhf.
[Build]    Preparing to unpack .../libexpat1-dev_2.1.0-6+deb8u4_armhf.deb ...
[Build]    Unpacking libexpat1-dev:armhf (2.1.0-6+deb8u4) ...
[Build]    Selecting previously unselected package libpython2.7-dev:armhf.
[Build]    Preparing to unpack .../libpython2.7-dev_2.7.9-2+deb8u1_armhf.deb ...
[Build]    Unpacking libpython2.7-dev:armhf (2.7.9-2+deb8u1) ...
[Build]    Selecting previously unselected package libpython-dev:armhf.
[Build]    Preparing to unpack .../libpython-dev_2.7.9-1_armhf.deb ...
[Build]    Unpacking libpython-dev:armhf (2.7.9-1) ...
[Build]    Selecting previously unselected package python2.7-dev.
[Build]    Preparing to unpack .../python2.7-dev_2.7.9-2+deb8u1_armhf.deb ...
[Build]    Unpacking python2.7-dev (2.7.9-2+deb8u1) ...
[Build]    Selecting previously unselected package python-dev.
[Build]    Preparing to unpack .../python-dev_2.7.9-1_armhf.deb ...
[Build]    Unpacking python-dev (2.7.9-1) ...
[Build]    Selecting previously unselected package scons.
[Build]    Preparing to unpack .../archives/scons_2.3.1-2_all.deb ...
[Build]    Unpacking scons (2.3.1-2) ...
[Build]    Selecting previously unselected package swig2.0.
[Build]    Preparing to unpack .../swig2.0_2.0.12-1_armhf.deb ...
[Build]    Unpacking swig2.0 (2.0.12-1) ...
[Build]    Selecting previously unselected package swig.
[Build]    Preparing to unpack .../swig_2.0.12-1_armhf.deb ...
[Build]    Unpacking swig (2.0.12-1) ...
[Build]    Setting up libpython2.7:armhf (2.7.9-2+deb8u1) ...
[Build]    Setting up libexpat1-dev:armhf (2.1.0-6+deb8u4) ...
[Build]    Setting up libpython2.7-dev:armhf (2.7.9-2+deb8u1) ...
[Build]    Setting up libpython-dev:armhf (2.7.9-1) ...
[Build]    Setting up python2.7-dev (2.7.9-2+deb8u1) ...
[Build]    Setting up python-dev (2.7.9-1) ...
[Build]    Setting up scons (2.3.1-2) ...
[Build]    Setting up swig2.0 (2.0.12-1) ...
[Build]    Setting up swig (2.0.12-1) ...
[Build]    Processing triggers for libc-bin (2.19-18+deb8u10) ...
[Build]     ---> a7555a100424
[Build]    Removing intermediate container 3e1972c9254a
[Build]    Step 3/10 : WORKDIR /usr/src/app
[Build]     ---> 7c512579da41
[Build]    Removing intermediate container 8ecd384cc369
[Build]    Step 4/10 : RUN git clone https://github.com/jgarff/rpi_ws281x.git && cd rpi_ws281x && scons && cd python && python setup.py install
[Build]     ---> Running in f92b8f337e74
[Build]    Cloning into 'rpi_ws281x'...
[Build]    scons: Reading SConscript files ...
[Build]    scons: done reading SConscript files.
[Build]    scons: Building targets ...
[Build]    Version version.h
[Build]    CC      main.o
[Build]    CC      mailbox.o
[Build]    CC      ws2811.o
[Build]    CC      pwm.o
[Build]    CC      pcm.o
[Build]    CC      dma.o
[Build]    CC      rpihw.o
[Build]    AR      libws2811.a
[Build]    RANLIB  libws2811.a
[Build]    LINK    test
[Build]    scons: done building targets.
[Build]    Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-5.7.zip
[Build]    Extracting in /tmp/tmphUEKPK
[Build]    Now working in /tmp/tmphUEKPK/setuptools-5.7
[Build]    Building a Setuptools egg in /usr/src/app/rpi_ws281x/python
[Build]    Traceback (most recent call last):
[Build]      File "setup.py", line 30, in <module>
[Build]        from setuptools.command.test import test as _test
[Build]      File "/tmp/tmphUEKPK/setuptools-5.7/setuptools/command/test.py", line 2, in <module>
[Build]        from unittest import TestLoader
[Build]      File "/usr/local/lib/python2.7/unittest/__init__.py", line 64, in <module>
[Build]        from .main import TestProgram, main
[Build]      File "/usr/local/lib/python2.7/unittest/main.py", line 7, in <module>
[Build]        from . import loader, runner
[Build]      File "/usr/local/lib/python2.7/unittest/runner.py", line 7, in <module>
[Build]        from .signals import registerResult
[Build]      File "/usr/local/lib/python2.7/unittest/signals.py", line 2, in <module>
[Build]        import weakref
[Build]      File "/usr/local/lib/python2.7/weakref.py", line 14, in <module>
[Build]        from _weakref import (
[Build]    ImportError: cannot import name _remove_dead_weakref
[Build]    /usr/src/app/rpi_ws281x/python/setuptools-5.7-py2.7.egg
[Build]    Traceback (most recent call last):
[Build]      File "setup.py", line 4, in <module>
[Build]        use_setuptools()
[Build]      File "/usr/src/app/rpi_ws281x/python/ez_setup.py", line 140, in use_setuptools
[Build]        return _do_download(version, download_base, to_dir, download_delay)
[Build]      File "/usr/src/app/rpi_ws281x/python/ez_setup.py", line 120, in _do_download
[Build]        _build_egg(egg, archive, to_dir)
[Build]      File "/usr/src/app/rpi_ws281x/python/ez_setup.py", line 69, in _build_egg
[Build]        raise IOError('Could not build the egg.')
[Build]    IOError: Could not build the egg.
[Build]    Removing intermediate container f92b8f337e74
[Error]    Build failed: The command '/bin/sh -c git clone https://github.com/jgarff/rpi_ws281x.git && cd rpi_ws281x && scons && cd python && python setup.py install' returned a non-zero code: 1
[Info]     Uploading successful layers to registry for caching purposes
[==================================================>] 100%
[Info]     Successfully updated cache.

remote: error: hook declined to update refs/heads/master
To git.resin.io:damianm/NewLock.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'damianm@git.resin.io:damianm/NewLock.git'
